[build]
    command   = "yarn run build"
    functions = "out_functions"
    publish   = "out_publish"

[functions]
    node_bundler = "esbuild"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[dev]
    functions = "out_functions"
    publish   = "out_publish"
    framework = "#static"
